package com.stellariz.testapp.config

object ApiTokenHolder  {
    const val API_TOKEN : String = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxZmViZDFjZmI0NzkwOWNkZWVmNjI4MGNmNGU3ZmQ3YyIsInN1YiI6IjYzMTg3MDMxMGYwZGE1MDA4MjU1Y2RmYiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.oErjGi4TFZO6lEU4Ay39ij481QCn_sAqjljSOhxGqik"
}